---
title: "Assessment Information"
description: |
  Updates on the course for each semester will be displayed here. These will include the important dates for the assessment every semester.  
  
  Please visit this page as often as possible to keep up to date.
output: 
  distill::distill_article:
    self_contained: true
---

## Assessment Date  

## {.tabset}  

### 20212  

**Assessment 1 (Taxonomy level:C2)**  

Week 7 - 21/5/2021 (Friday, 9am - 10.30am) 

- Topic 1 (15 marks)  
- Topic 2 (25 marks)  
  - organizing qualitative data & numerical descriptive measures for ungrouped data (8 marks)  
  - Numerical descriptive measures for grouped data (17 marks)  

***

**Assessment 2**  

Week 12 - 2 July 2021, (Friday, 9am-10.30am)  

- Topic 3 (C3) - 20 marks (2 org)  
- Topic 4 (C3) - 10 marks (1 org)  
- Topic 5 (C3) - 10 marks (1 org)  

***

**Group Project**  

Due Date - **_Week 13 (10 July 2021)_**

All project must be submitted in soft-copy either in .docx or .pdf format.  
Submission of the final report is by uploading the relevant files into the instructor Google Drive folder or any other means as instructed by your respective supervisors.  

Students are required to communicate with respective supervisors for group project submission.  

***

**Final Examination**  

Saturday  
24 July 2021
2:15 - 5:15 PM
